
# Streamlit Secrets Configuration
# Create this file in your project: .streamlit/secrets.toml
# DO NOT commit this file to version control!

GEMINI_API_KEY = "AIzaSyC35mil4vDAAmBkEVFVGyY8XEA5qGP3HSs"

# Instructions:
# 1. Get your free Gemini API key from: https://makersuite.google.com/app/apikey
# 2. Replace "your-gemini-api-key-here" with your actual API key
# 3. For Streamlit Cloud deployment, add this as a secret in your app settings